name: test bash

on:
  workflow_dispatch:
    inputs:
      asset-name:
        description: 'The asset name.'
        required: false

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Evaluate asset-name
        shell: bash
        run: echo "##[set-output name=name;][[ ! -z ${{ inputs.asset-name }} ]] && echo ${{ inputs.asset-name }} || echo ${{ github.event.repository.name }}-${{ inputs.release-version }}-all.zip"
        id: evaluate_asset_name

      - name: Use asset-name
        shell: bash
        run: echo steps.evaluate_asset_name.outputs.name
        id: use_asset_name

