name: test bash

on:
  workflow_dispatch:
    inputs:
      asset-name:
        description: 'The asset name.'
        required: false

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Echo
        shell: bash
        run: echo my var ${{ github.event.inputs.asset-name }}
        
      - name: Evaluate asset-name
        shell: bash
        run: |
          if [ "$ASSET_NAME" == "" ]; then
            echo ::set-output name=name:: ${{ github.event.repository.name }}-all.zip
          else
            echo ::set-output name=name:: "$ASSET_NAME"
          fi
        env:
          ASSET_NAME: ${{ github.event.inputs.asset-name }}
        id: evaluate_asset_name

      - name: Use asset-name
        shell: bash
        run: echo "${{ steps.evaluate_asset_name.outputs.name }}"
        id: use_asset_name

